//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event.DOM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml.Linq;

    public partial class Equipment: BaseDOM
    {
        public int EquipmentID { get; set; }

        [DisplayName("Equipment Name")]
        public string EquipmentName { get; set; }
        public string EquipmentFilename { get; set; }
        [Display(Name = "Equipment Image")]
        public string EquipmentFilePath { get; set; }
        public Nullable<int> EquipmentCost { get; set; }
    }
}
