//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event.DOM
{
    using System;
    
    public partial class Venue
    {
        public int VenueID { get; set; }
        public string VenueName { get; set; }
        public string VenueFilename { get; set; }
        public string VenueFilePath { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<int> VenueCost { get; set; }
    }
}
